CREATE TABLE zaasmis.dbo.CY_CGZHJY (
  id INT PRIMARY KEY NOT NULL,
  project_num VARCHAR(50),
  project_year INT,
  depart_id VARCHAR(10),
  depart VARCHAR(50),
  project_type VARCHAR(50),
  project_type_code VARCHAR(50),
  project_name VARCHAR(150),
  zaas_tech_type VARCHAR(50),
  zaas_code VARCHAR(50),
  customer_depart VARCHAR(50),
  depart_full_name VARCHAR(50),
  project_person VARCHAR(50),
  start_date DATETIME,
  end_date DATETIME,
  project_summary NTEXT,
  intention_amount NUMERIC(19,2),
  intention_amount_explain NTEXT,
  sign_amount NUMERIC(19,2),
  remarks NTEXT,
  submiter_id NUMERIC(18),
  submiter VARCHAR(50),
  assessor_id NUMERIC(18),
  assessor VARCHAR(50),
  submit_state INT,
  assess_state INT,
  download_state INT,
  join_state INT
);